-- Cross-module persistence and booking hardening for TourFlow.

alter table public.attractions
  add column if not exists geofence_radius_m integer not null default 200
  check (geofence_radius_m between 25 and 2000);

-- Organization members may configure slots, but reservation totals are owned
-- exclusively by the security-definer booking functions.
revoke update on public.attraction_slots from authenticated;
grant update (starts_at, ends_at, maximum_capacity, status)
  on public.attraction_slots to authenticated;

create table public.feedback (
  id uuid primary key default gen_random_uuid(),
  tourist_id uuid not null references public.profiles (id) on delete cascade,
  booking_id uuid not null references public.bookings (id) on delete cascade,
  attraction_id uuid not null references public.attractions (id) on delete cascade,
  overall_rating integer not null check (overall_rating between 1 and 5),
  crowd_comfort integer not null check (crowd_comfort between 1 and 5),
  tags text[] not null default '{}',
  comment text not null default '' check (char_length(comment) <= 2000),
  created_at timestamptz not null default now(),
  unique (tourist_id, booking_id)
);

create type public.report_status as enum ('new', 'in_progress', 'resolved');
create type public.report_priority as enum ('low', 'medium', 'urgent');

create table public.issue_reports (
  id uuid primary key default gen_random_uuid(),
  report_code text not null unique default
    ('R-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  tourist_id uuid not null references public.profiles (id) on delete cascade,
  attraction_id uuid not null references public.attractions (id) on delete cascade,
  booking_id uuid not null references public.bookings (id) on delete cascade,
  category text not null check (category in
    ('Overcrowding', 'Safety', 'Facility', 'Accessibility', 'Others')),
  location_note text not null check (char_length(trim(location_note)) between 2 and 200),
  description text not null check (char_length(trim(description)) between 5 and 2000),
  priority public.report_priority not null default 'medium',
  status public.report_status not null default 'new',
  assigned_to uuid references public.profiles (id) on delete set null,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table public.report_events (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.issue_reports (id) on delete cascade,
  actor_id uuid not null references public.profiles (id),
  event_type text not null check (event_type in ('created', 'started', 'resolved')),
  note text,
  created_at timestamptz not null default now()
);

create table public.attraction_check_ins (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null unique references public.bookings (id) on delete cascade,
  tourist_id uuid not null references public.profiles (id) on delete cascade,
  attraction_id uuid not null references public.attractions (id) on delete cascade,
  checked_in_at timestamptz not null default now(),
  checked_out_at timestamptz,
  distance_m numeric(10, 2) not null check (distance_m >= 0),
  source text not null default 'geofence' check (source in ('geofence', 'staff_scan')),
  check (checked_out_at is null or checked_out_at >= checked_in_at)
);

create index issue_reports_tourist_created_idx
  on public.issue_reports (tourist_id, created_at desc);
create index issue_reports_attraction_status_idx
  on public.issue_reports (attraction_id, status, created_at desc);
create index attraction_check_ins_live_idx
  on public.attraction_check_ins (attraction_id, checked_in_at desc)
  where checked_out_at is null;

create trigger issue_reports_set_updated_at
before update on public.issue_reports
for each row execute function public.set_updated_at();

create function public.prepare_feedback()
returns trigger language plpgsql security definer set search_path = '' as $$
declare selected_booking public.bookings;
begin
  select * into selected_booking from public.bookings where id = new.booking_id;
  if selected_booking.id is null or selected_booking.tourist_id <> (select auth.uid()) then
    raise exception 'BOOKING_ACCESS_DENIED';
  end if;
  if selected_booking.status <> 'completed' then raise exception 'VISIT_NOT_COMPLETED'; end if;
  new.tourist_id := selected_booking.tourist_id;
  select slot.attraction_id into new.attraction_id
  from public.attraction_slots slot where slot.id = selected_booking.slot_id;
  return new;
end;
$$;

create trigger feedback_prepare
before insert or update on public.feedback
for each row execute function public.prepare_feedback();

create function public.prepare_issue_report()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  new.tourist_id := (select auth.uid());
  if not exists (
    select 1 from public.bookings booking
    where booking.id = new.booking_id and booking.tourist_id = (select auth.uid())
  ) then raise exception 'BOOKING_ACCESS_DENIED'; end if;
  select slot.attraction_id into new.attraction_id
  from public.bookings booking
  join public.attraction_slots slot on slot.id = booking.slot_id
  where booking.id = new.booking_id;
  new.priority := case when new.category = 'Safety' then 'urgent'::public.report_priority
    else 'medium'::public.report_priority end;
  return new;
end;
$$;

create trigger issue_report_prepare
before insert on public.issue_reports
for each row execute function public.prepare_issue_report();

-- This trigger protects existing deployments of the original booking RPC as
-- well as fresh installations. It serializes each tourist's inserts and
-- validates both adjacent visits immediately before the booking is written.
create function public.validate_booking_insert()
returns trigger language plpgsql security definer set search_path = '' as $$
declare selected_slot public.attraction_slots;
declare previous_record record;
declare next_record record;
begin
  if (select auth.uid()) is null then return new; end if;
  perform pg_advisory_xact_lock(hashtextextended(new.tourist_id::text, 0));
  select * into selected_slot from public.attraction_slots where id = new.slot_id;
  if exists (
    select 1 from public.bookings booking
    join public.attraction_slots slot on slot.id = booking.slot_id
    where booking.tourist_id = new.tourist_id and booking.status = 'confirmed'
      and tstzrange(slot.starts_at, slot.ends_at, '[)')
        && tstzrange(selected_slot.starts_at, selected_slot.ends_at, '[)')
  ) then raise exception 'BOOKING_OVERLAP'; end if;
  select slot.ends_at, slot.attraction_id into previous_record
  from public.bookings booking
  join public.attraction_slots slot on slot.id = booking.slot_id
  where booking.tourist_id = new.tourist_id and booking.status = 'confirmed'
    and slot.ends_at <= selected_slot.starts_at
  order by slot.ends_at desc limit 1;
  if previous_record.ends_at is not null
    and extract(epoch from (selected_slot.starts_at - previous_record.ends_at)) / 60
      < public.estimated_travel_minutes(previous_record.attraction_id, selected_slot.attraction_id)
  then raise exception 'INSUFFICIENT_TRAVEL_TIME'; end if;
  select slot.starts_at, slot.attraction_id into next_record
  from public.bookings booking
  join public.attraction_slots slot on slot.id = booking.slot_id
  where booking.tourist_id = new.tourist_id and booking.status = 'confirmed'
    and slot.starts_at >= selected_slot.ends_at
  order by slot.starts_at limit 1;
  if next_record.starts_at is not null
    and extract(epoch from (next_record.starts_at - selected_slot.ends_at)) / 60
      < public.estimated_travel_minutes(selected_slot.attraction_id, next_record.attraction_id)
  then raise exception 'INSUFFICIENT_TRAVEL_TIME'; end if;
  return new;
end;
$$;

create trigger bookings_validate_insert
before insert on public.bookings
for each row execute function public.validate_booking_insert();

create function public.resolve_issue_report(target_report_id uuid, note text)
returns public.issue_reports language plpgsql security definer set search_path = '' as $$
declare selected_report public.issue_reports;
begin
  select * into selected_report from public.issue_reports
  where id = target_report_id for update;
  if selected_report.id is null then raise exception 'REPORT_NOT_FOUND'; end if;
  if not public.is_administrator() and not exists (
    select 1 from public.attractions attraction
    where attraction.id = selected_report.attraction_id
      and public.is_organization_member(attraction.organization_id)
  ) then raise exception 'REPORT_ACCESS_DENIED'; end if;
  if char_length(trim(note)) < 3 then raise exception 'RESOLUTION_NOTE_REQUIRED'; end if;
  update public.issue_reports set status = 'resolved', resolution_note = trim(note),
    assigned_to = (select auth.uid()), resolved_at = now()
  where id = target_report_id returning * into selected_report;
  insert into public.report_events (report_id, actor_id, event_type, note)
  values (target_report_id, (select auth.uid()), 'resolved', trim(note));
  return selected_report;
end;
$$;

create function public.check_in_booking(
  target_booking_id uuid, current_latitude double precision,
  current_longitude double precision
)
returns public.attraction_check_ins language plpgsql security definer set search_path = '' as $$
declare selected_booking public.bookings;
declare selected_slot public.attraction_slots;
declare selected_attraction public.attractions;
declare distance_m double precision;
declare created_check_in public.attraction_check_ins;
begin
  select * into selected_booking from public.bookings where id = target_booking_id for update;
  if selected_booking.id is null or selected_booking.tourist_id <> (select auth.uid()) then
    raise exception 'BOOKING_ACCESS_DENIED';
  end if;
  if selected_booking.status <> 'confirmed' then raise exception 'BOOKING_NOT_ACTIVE'; end if;
  select * into selected_slot from public.attraction_slots where id = selected_booking.slot_id;
  if now() not between selected_slot.starts_at - interval '2 hours' and selected_slot.ends_at then
    raise exception 'CHECK_IN_TIME_INVALID';
  end if;
  select * into selected_attraction from public.attractions
  where id = selected_slot.attraction_id;
  if selected_attraction.latitude is null or selected_attraction.longitude is null then
    raise exception 'ATTRACTION_LOCATION_MISSING';
  end if;
  distance_m := 6371000 * 2 * asin(sqrt(
    power(sin(radians(current_latitude - selected_attraction.latitude) / 2), 2) +
    cos(radians(selected_attraction.latitude)) * cos(radians(current_latitude)) *
    power(sin(radians(current_longitude - selected_attraction.longitude) / 2), 2)
  ));
  if distance_m > selected_attraction.geofence_radius_m then raise exception 'OUTSIDE_GEOFENCE'; end if;
  insert into public.attraction_check_ins
    (booking_id, tourist_id, attraction_id, distance_m)
  values (selected_booking.id, selected_booking.tourist_id,
    selected_attraction.id, distance_m)
  on conflict (booking_id) do update set distance_m = excluded.distance_m
  returning * into created_check_in;
  return created_check_in;
end;
$$;

revoke execute on function public.resolve_issue_report(uuid, text) from public, anon;
revoke execute on function public.check_in_booking(uuid, double precision, double precision) from public, anon;
grant execute on function public.resolve_issue_report(uuid, text) to authenticated;
grant execute on function public.check_in_booking(uuid, double precision, double precision) to authenticated;

alter table public.feedback enable row level security;
alter table public.issue_reports enable row level security;
alter table public.report_events enable row level security;
alter table public.attraction_check_ins enable row level security;

revoke all on public.feedback, public.issue_reports, public.report_events,
  public.attraction_check_ins from anon, authenticated;
grant select, insert, update, delete on public.feedback to authenticated;
grant select, insert on public.issue_reports to authenticated;
grant select on public.report_events, public.attraction_check_ins to authenticated;

create policy feedback_owner_all on public.feedback for all to authenticated
using (tourist_id = (select auth.uid()))
with check (tourist_id = (select auth.uid()));
create policy feedback_operator_select on public.feedback for select to authenticated using (
  public.is_administrator() or exists (
    select 1 from public.attractions attraction
    where attraction.id = attraction_id
      and public.is_organization_member(attraction.organization_id)
  )
);
create policy issue_reports_owner_select on public.issue_reports for select to authenticated
using (tourist_id = (select auth.uid()));
create policy issue_reports_owner_insert on public.issue_reports for insert to authenticated
with check (tourist_id = (select auth.uid()));
create policy issue_reports_operator_select on public.issue_reports for select to authenticated using (
  public.is_administrator() or exists (
    select 1 from public.attractions attraction
    where attraction.id = attraction_id
      and public.is_organization_member(attraction.organization_id)
  )
);
create policy report_events_related_select on public.report_events for select to authenticated using (
  exists (select 1 from public.issue_reports report where report.id = report_id)
);
create policy check_ins_related_select on public.attraction_check_ins for select to authenticated using (
  tourist_id = (select auth.uid()) or public.is_administrator() or exists (
    select 1 from public.attractions attraction
    where attraction.id = attraction_id
      and public.is_organization_member(attraction.organization_id)
  )
);
